development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

production:
  adapter: mysql2
  encoding: utf8
  database: my_db_name
  username: user
  password: password
  host: 127.0.0.1
  port: 3306
